# x = input("Enter Ist Value : ")
# y = input("Enter 2nd Value : ")
# z = x + y
# print("x = ", x, type(x))
# print("y = ", y, type(y))
# print("z = ", z, type(z))
# # x = input("Enter Ist Value : ")
# y = input("Enter 2nd Value : ")
# z = x + y
# print("x = ", x, type(x))
# print("y = ", y, type(y))
# print("z = ", z, type(z))
x = input("Enter Ist Value : ")
y = int(input("Enter 2nd Value : "))
z = x + y
print("x = ", x, type(x))
print("y = ", y, type(y))
print("z = ", z, type(z))
